[build]
  command = "npm install && npm run build && npm run export"
  publish = "out"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

